### PR TITLE
videoclip evaluation notebook/tutorial

### PR DESCRIPTION
**Pull request by sophiazhi**
Summary:
Add notebook tutorial for VideoCLIP evaluation using pretrained checkpoint.
- `retrieval/evaluation.ipynb`: notebook with step-by-step instructions for setting up model, calling model, and getting predictions

Test plan:
Run notebook

Note that vscode is incapable of rendering video/audio in notebooks (see [issue](https://github.com/microsoft/vscode/issues/118275)) and github doesn't display the videos in output cells. Embedded videos can be played in google colab ([link to this tutorial in colab](https://colab.research.google.com/drive/1zCU0KPzFKns07aVbSlN_1c8gtKXG0ke2?usp=sharing)) or in jupyter lab. 

To install jupyterlab, convert your `torch-multimodal` conda env into a kernel, and launch jupyter lab:
```
(base) conda install -c conda-forge jupyterlab
(base) conda activate torch-multimodal
(torch-multimodal) conda install ipykernel
(torch-multimodal) ipython kernel install --user --name=torch-multimodal
(torch-multimodal) conda deactivate
(base) jupyter lab
```

### CODE REVIEW

**Review by ankitade — COMMENTED** [review]
looks great. can u do forward on the model instead of lightning module?

**Comment by sophiazhi** [comment]
> can u do forward on the model instead of lightning module?

yup i can make that change, but just wondering what's the reasoning for that?

**Review by ankitade — APPROVED** [review]
why is pretrained_text / video set to False?

**Comment by sophiazhi** [comment]
> why is pretrained_text / video set to False?

if i set those to True, then the model will load a different set of weights (pretrained on general datasets, not mugen) before replacing them with the checkpoint weights from aws (trained on mugen). so i set them to False since i want to load the checkpoint weights anyway

**Pull request closed without merging**
