### PR TITLE
[Unification][ALBEF] Refactor ALBEF with TransformerEncoder

### PR DESCRIPTION
**Pull request by RdoubleA**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #253
* #249
* #248
* __->__ #244
* #243
* #240
* #239

## Summary
Replace `ALBEFTransformerEncoder` with unified class. Refactor some transformer outputs.

## Test plan
`pytest -vv`

Differential Revision: [D38506997](https://our.internmc.facebook.com/intern/diff/D38506997)

### CODE REVIEW

**Comment by RdoubleA** [comment]
@RdoubleA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38506997).

**Comment by RdoubleA** [comment]
@RdoubleA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38506997).

**Comment by RdoubleA** [comment]
@RdoubleA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38506997).

**Comment by RdoubleA** [comment]
@RdoubleA has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38506997).

**Review by ebsmothers — APPROVED** [review]

**Pull request closed without merging**
