### PR TITLE
[FLAVA]Change some initialization orders and corresponding tests

### PR DESCRIPTION
**Pull request by ankitade**
- Currently the projections are part of contrastive loss which means we need to use "flava for pretraining" for zero shot. This is weird since zero shot should just involve core model (and not pretraining model)
- The next PR in this stack tried to fix it but broke the tests because of changing initialization order of several components
- So splitting that PR into 2 to make sure my logic changes are not actually breaking anything
   1. This PR which simply changes the initialization order of codebook and contrastive loss and changes the test assert values
   2. Next PR which makes projections part of flava model and doesn't touch the tests

Test plan 
pytest 

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #195
* #132
* #131
* #106
* __->__ #105

Differential Revision: [D37466221](https://our.internmc.facebook.com/intern/diff/D37466221)

### CODE REVIEW

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37466221).

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37466221).

**Review by ebsmothers — APPROVED** [review]

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37466221).

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37466221).

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37466221).

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37466221).

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37466221).

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37466221).

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37466221).

**Pull request closed without merging**
