### PR TITLE
[Refactor] Make dropout layer optional in MLP

### PR DESCRIPTION
**Pull request by langong347**
Summary:
The transformer layer of Multigen uses an MLP block without dropout so we want to make dropout optional in the current MLP layer when the dropout prob is provided as `0.0`.

Test Plan:
```
(torchmm) langong-mbp:gpt_attention langong$ python -m pytest --cov=torchmultimodal/modules/layers/ test/modules/layers/test_mlp.py -vv
================================================================================ test session starts =================================================================================
platform darwin -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0 -- /Users/langong/local/miniconda3/envs/torchmm/bin/python
cachedir: .pytest_cache
rootdir: /Users/langong/gpt_attention
plugins: cov-3.0.0
collected 6 items

test/modules/layers/test_mlp.py::TestMLP::test_activation_and_normalization PASSED                                                                                             [ 16%]
test/modules/layers/test_mlp.py::TestMLP::test_dropout_default PASSED                                                                                                          [ 33%]
test/modules/layers/test_mlp.py::TestMLP::test_no_dropout PASSED                                                                                                               [ 50%]
test/modules/layers/test_mlp.py::TestMLP::test_no_hidden_layers PASSED                                                                                                         [ 66%]
test/modules/layers/test_mlp.py::TestMLP::test_pass_hidden_dims PASSED                                                                                                         [ 83%]
test/modules/layers/test_mlp.py::TestMLP::test_torchscript PASSED                                                                                                              [100%]

---------- coverage: platform darwin, python 3.8.13-final-0 ----------
Name                                                   Stmts   Miss  Cover
--------------------------------------------------------------------------
torchmultimodal/modules/layers/attention.py               97     97     0%
torchmultimodal/modules/layers/codebook.py                81     81     0%
torchmultimodal/modules/layers/conv.py                    74     74     0%
torchmultimodal/modules/layers/mlp.py                     23      1    96%
torchmultimodal/modules/layers/normalizations.py           7      7     0%
torchmultimodal/modules/layers/position_embedding.py      38     38     0%
torchmultimodal/modules/layers/transformer.py            133    133     0%
--------------------------------------------------------------------------
TOTAL                                                    453    431     5%


=========================== 6 passed in 1.82s ====================
```

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #84
* #69
* #68
* #67

Differential Revision: [D37116648](https://our.internmc.facebook.com/intern/diff/D37116648)

### CODE REVIEW

**Comment by langong347** [comment]
@ankitade In our MLP the dropout argument is a floating number with default value `0.3`. `0.0` is compatible with the floating type and tells the MLP that the caller module does not need a dropout layer.

**Comment by langong347** [comment]
@langong347 has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37116648).

**Comment by ankitade** [comment]
its ok for this case, but in general we need not change a model just for alignment with ckpt (instead do the opposite of it)

**Comment by langong347** [comment]
@ankitade  No, it's not due to checkpointing. The MLP block in the transformer layer does not require dropout. Our existing MLP module did not have that flexibility to opt out of dropout.

**Comment by ankitade** [comment]
0 dropout is anyways same as no dropout right?

**Comment by langong347** [comment]
> 0 dropout is anyways same as no dropout right?

Theoretically yes. But it'd be cleaner to simply leave the layer out.

**Pull request closed without merging**
