### PR TITLE
[diffusion_labs] Move attention and res blocks under modules

### PR DESCRIPTION
**Pull request by ebsmothers**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #490
* #489
* #488

Differential Revision: [D50288362](https://our.internmc.facebook.com/intern/diff/D50288362)

### CODE REVIEW

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D50288362).

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D50288362).

**Review by pbontrager — CHANGES_REQUESTED** [review]
I don't personally agree with this diff. If these modules can live as generic layers, then they should be under torchmultimodal/modules/layers while if they're just specific to ADM then they should be under adm_unet. I think we should keep the diffusion folders as focused on diffusion as possible and try to keep out other things.

**Comment by ebsmothers** [comment]
@pbontrager I guess there are three possible places for these components: diffusion_labs/models/adm_unet/..., diffusion_labs/modules/..., and torchmultimodal/modules/.... I agree that the first location should be for components specific to ADM UNet. The second should be for more generic diffusion components (i.e. not tied to ADM specifically), while components in the third location should have use for other non-diffusion cases. 

Based on those conditions I think it should be either option (1) or (2), since I'm not aware of any models outside of diffusion_labs that would use these components. @abhinavarora mentioned that there are other diffusion models that can benefit from these components which is why I opened this PR. But if that's not the case, we can just close this and leave them where they are. Let me know what both of you think here.

**Comment by pbontrager** [comment]
> @pbontrager I guess there are three possible places for these components: diffusion_labs/models/adm_unet/..., diffusion_labs/modules/..., and torchmultimodal/modules/.... I agree that the first location should be for components specific to ADM UNet. The second should be for more generic diffusion components (i.e. not tied to ADM specifically), while components in the third location should have use for other non-diffusion cases.
> 
> Based on those conditions I think it should be either option (1) or (2), since I'm not aware of any models outside of diffusion_labs that would use these components. @abhinavarora mentioned that there are other diffusion models that can benefit from these components which is why I opened this PR. But if that's not the case, we can just close this and leave them where they are. Let me know what both of you think here.

I believe they should stay with adm_unet until they start being reused as they may require modifications at that time. At that time I think they should be moved to option (3) because, while the architecture is being used for diffusion training, neural networks are still pretty generic for all types of training. I'm open to discussing this further though.

**Comment by abhinavarora** [comment]
My understanding is that these components are specific implementations of general concepts that have been popularized by prominent diffusion researchers (OpenAI, Stability, etc).  I don't see them being used in any other models outside of those that build their code on top of OpenAI and StabilityAI repos. For example, this implementation of resnet blocks is quite different from the generic ones found in TorchVision.

Hence in my opinion, only option 1) and 2) make sense. To me option 2) makes more sense because components like `ADMResBlock` are used by all other models (VAE and LDM UNet). I am okay with 1) as well if you want to unblock the PT Conf works and punt this discussion to later.

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D50288362).

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D50288362).

**Comment by ebsmothers** [comment]
Closing this since we are not planning to land these changes right now

**Pull request closed without merging**
