### PR TITLE
ADMStack and ADMResBlock changes

### PR DESCRIPTION
**Pull request by ebsmothers**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #490
* __->__ #489
* #488

Differential Revision: [D50288363](https://our.internmc.facebook.com/intern/diff/D50288363)

### CODE REVIEW

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D50288363).

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D50288363).

**Review by pbontrager — APPROVED** [review]
Thanks for bringing over these changes, looks good.

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D50288363).

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D50288363).

**Pull request closed without merging**
