### PR TITLE
[examples] Extract MultiDataLoader/Module to examples/common/data

### PR DESCRIPTION
**Pull request by IvanKobzarev**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #94
* __->__ #93

We want to extract common functionality (MultiDataModule, MultiDataLoader) to be shared between flava and other examples.

Introducing `examples/common/data/multidata.py`. To be able to use it from `examples/flava` we need to be in one python package - `examples` =>

Renaming imports with prefix `flava.`.

Training flava after this change will be `python -m flava.train config=...` to run it within `examples` package

Differential Revision: [D37188387](https://our.internmc.facebook.com/intern/diff/D37188387)

### CODE REVIEW

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37188387).

**Review by ebsmothers — COMMENTED** [review]
Overall these changes look good. One question though: why move the requirements file up a level? I see the value in making a lot of these data utils common (which necessitates at least some dependencies in `examples/`), but I think the idea is for each example to have its own distinct set of requirements. For instance, someone importing a generic data util probably does not want to take a dep on DALL-E in general.

**Comment by IvanKobzarev** [comment]
> Overall these changes look good. One question though: why move the requirements file up a level? I see the value in making a lot of these data utils common (which necessitates at least some dependencies in `examples/`), but I think the idea is for each example to have its own distinct set of requirements. For instance, someone importing a generic data util probably does not want to take a dep on DALL-E in general.

Thanks, I agree, it will be better to have separate requirements files per example model.

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37188387).

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37188387).

**Review by ebsmothers — APPROVED** [review]
Other than the one minor comment, this looks good to go.

**Comment by IvanKobzarev** [comment]
@ivankobzarev has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D37188387).

**Pull request closed without merging**
