### PR TITLE
[MUGEN][Doc] Fix tutorial links of retrieval example

### PR DESCRIPTION
**Pull request by langong347**
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #356
* #357
* __->__ #355
* #354

Summary:
As titled.

Test Plan:
Verified that the links would work in the public domain.

Differential Revision: [D40421055](https://our.internmc.facebook.com/intern/diff/D40421055)

### CODE REVIEW

**Comment by langong347** [comment]
cc @sophiazhi

**Comment by langong347** [comment]
@langong347 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40421055).

**Comment by langong347** [comment]
@langong347 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40421055).

**Review by ebsmothers — APPROVED** [review]

**Comment by langong347** [comment]
@langong347 has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D40421055).

**Pull request closed without merging**
