### PR TITLE
[FLAVA] Use one config per model for native pytorch script

### PR DESCRIPTION
**Pull request by ankitade**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #286

Test plan:
Sanity check 
torchrun --master_port=1256 --nproc_per_node=8 -m flava.native.train config=flava/native/configs/pretrain_debug.yaml

Differential Revision: [D39049359](https://our.internmc.facebook.com/intern/diff/D39049359)

### CODE REVIEW

**Comment by ankitade** [comment]
@deankita has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39049359).

**Comment by ankitade** [comment]
@deankita has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39049359).

**Review by edward-io — APPROVED** [review]

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39049359).

**Comment by ankitade** [comment]
@ankitade has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D39049359).

**Pull request closed without merging**
