### PR TITLE
[TorchMultimodal][chore] Fix import sorting inconsistency

### PR DESCRIPTION
**Pull request by ebsmothers**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #12

Changes in this PR:
- Disable first_party_detection in usort
- Update CONTRIBUTING with black and usort versions
- Run ufmt on the entire repo to fix import order issues

Differential Revision: [D35377751](https://our.internmc.facebook.com/intern/diff/D35377751)

### CODE REVIEW

**Review by langong347 — APPROVED** [review]

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35377751).

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35377751).

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35377751).

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D35377751).

**Pull request closed without merging**
