### PR TITLE
[MDETR] Move model components into models/mdetr

### PR DESCRIPTION
**Pull request by ebsmothers**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #246
* #232
* #231
* __->__ #230

Summary: Mostly just moving around existing components. Create a new directory models/mdetr
and put text and image encoders in there. Also move transformer components into their own file.
This is prep for the next PR, which will move task-specific models into mdetr/model.py, so taking
the transformer stuff out will make the file clearer.

Test plan:

```
python -m pytest -vv

```

Differential Revision: [D38467125](https://our.internmc.facebook.com/intern/diff/D38467125)

### CODE REVIEW

**Review by RdoubleA — APPROVED** [review]
clean imports, you love to see it

**Review by langong347 — APPROVED** [review]

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38467125).

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38467125).

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38467125).

**Comment by ebsmothers** [comment]
@ebsmothers has imported this pull request.  If you are a Facebook employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D38467125).

**Pull request closed without merging**
